### ISSUE TITLE
opensignalsreader.py breaks in Python 3

### ISSUE THREAD

**Issue by JohnDoenut** [PGomes92/opensignalsreader#2]
Hi @PGomes92 ,

the following line breaks opensignalreader.py in Python 3:

https://github.com/PGomes92/opensignalsreader/blob/b35895d53a8982aecf9243e9304f001912cceafc/opensignalsreader/opensignalsreader.py#L134

In Python 3, dict.keys() returns a dict_keys object which cannot be indexed. Using list (dict.keys()) should fix that.

**Comment by PGomes92** [comment]
Hi @JohnDoenut,

Thanks for the feedback and opening this issue! 

At the time I wrote this package I was working under Python 2.7 only and I did not test it under Python 3.X. Anyhow, I will test it properly under Python 3.X and update a fully working package as soon as I have the chance to work on it again.

**Comment by JohnDoenut** [comment]
Let me know if I can help. I'm happy to try and tackle a well defined issue.
